apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: supremejunction-com-tls
spec:
  secretName: supremejunction-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: supremejunction.com
  dnsNames:
    - supremejunction.com
    - www.supremejunction.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
         - supremejunction.com
         - www.supremejunction.com
